### ISSUE TITLE
"User documentation will be made available as the campaign progresses."

### ISSUE THREAD

**Issue by capiman** [greatscottgadgets/cynthion-hardware#17]
Many thanks for shipping Cynthion. It seems to work, but I am missing documentation.
Or it is there but I cannot put all small parts together.

Would it be possible to write/add User documentation:

- I assume only Linux x86/x64 is supported? Windows not? Snapdragon ARM64 not? Raspberry PI not? Or supported?
- which show where to add which cable for each use case (e.g. analyzer use case, where to connect controlling PC, where to connection USB host, where to connect USB device under test)
- what steps are needed in which order to get the analyzer (at least for this main use case) running
- what is needed to run as root, or can everthing run in user mode?
- and when it was running already running once, which steps must be called again?
- there is written that there a LEDs and which function they have, but not which function when it is blue/pink(red)?

**Comment by mossmann** [comment]
We've been working hard on software and documentation. The main documentation for Cynthion is built from the software repo and is available here: https://cynthion.readthedocs.io/

We support Linux, macOS, and Windows.

There is also separate documentation for Packetry, our USB analysis software: https://packetry.readthedocs.io/
